// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: src/proto/bank-account.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface GetBankAccountsRequest {
  telegramId: number;
}

export interface BankAccount {
  uuid: string;
  balance: number;
  currency: string;
  title: string;
  emoji: string;
  isInTotalBalance: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface GetBankAccountsResponse {
  status: boolean;
  bankAccounts: BankAccount[];
}

function createBaseGetBankAccountsRequest(): GetBankAccountsRequest {
  return { telegramId: 0 };
}

export const GetBankAccountsRequest: MessageFns<GetBankAccountsRequest> = {
  encode(message: GetBankAccountsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.telegramId !== 0) {
      writer.uint32(8).int64(message.telegramId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBankAccountsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBankAccountsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.telegramId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBankAccountsRequest {
    return { telegramId: isSet(object.telegramId) ? globalThis.Number(object.telegramId) : 0 };
  },

  toJSON(message: GetBankAccountsRequest): unknown {
    const obj: any = {};
    if (message.telegramId !== 0) {
      obj.telegramId = Math.round(message.telegramId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBankAccountsRequest>, I>>(base?: I): GetBankAccountsRequest {
    return GetBankAccountsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBankAccountsRequest>, I>>(object: I): GetBankAccountsRequest {
    const message = createBaseGetBankAccountsRequest();
    message.telegramId = object.telegramId ?? 0;
    return message;
  },
};

function createBaseBankAccount(): BankAccount {
  return {
    uuid: "",
    balance: 0,
    currency: "",
    title: "",
    emoji: "",
    isInTotalBalance: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const BankAccount: MessageFns<BankAccount> = {
  encode(message: BankAccount, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    if (message.balance !== 0) {
      writer.uint32(16).int64(message.balance);
    }
    if (message.currency !== "") {
      writer.uint32(26).string(message.currency);
    }
    if (message.title !== "") {
      writer.uint32(34).string(message.title);
    }
    if (message.emoji !== "") {
      writer.uint32(42).string(message.emoji);
    }
    if (message.isInTotalBalance !== false) {
      writer.uint32(48).bool(message.isInTotalBalance);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(66).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BankAccount {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBankAccount();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.balance = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.emoji = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isInTotalBalance = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BankAccount {
    return {
      uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "",
      balance: isSet(object.balance) ? globalThis.Number(object.balance) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : "",
      isInTotalBalance: isSet(object.isInTotalBalance) ? globalThis.Boolean(object.isInTotalBalance) : false,
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
    };
  },

  toJSON(message: BankAccount): unknown {
    const obj: any = {};
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (message.balance !== 0) {
      obj.balance = Math.round(message.balance);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.emoji !== "") {
      obj.emoji = message.emoji;
    }
    if (message.isInTotalBalance !== false) {
      obj.isInTotalBalance = message.isInTotalBalance;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BankAccount>, I>>(base?: I): BankAccount {
    return BankAccount.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BankAccount>, I>>(object: I): BankAccount {
    const message = createBaseBankAccount();
    message.uuid = object.uuid ?? "";
    message.balance = object.balance ?? 0;
    message.currency = object.currency ?? "";
    message.title = object.title ?? "";
    message.emoji = object.emoji ?? "";
    message.isInTotalBalance = object.isInTotalBalance ?? false;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseGetBankAccountsResponse(): GetBankAccountsResponse {
  return { status: false, bankAccounts: [] };
}

export const GetBankAccountsResponse: MessageFns<GetBankAccountsResponse> = {
  encode(message: GetBankAccountsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== false) {
      writer.uint32(8).bool(message.status);
    }
    for (const v of message.bankAccounts) {
      BankAccount.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBankAccountsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBankAccountsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.bankAccounts.push(BankAccount.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBankAccountsResponse {
    return {
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      bankAccounts: globalThis.Array.isArray(object?.bankAccounts)
        ? object.bankAccounts.map((e: any) => BankAccount.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetBankAccountsResponse): unknown {
    const obj: any = {};
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.bankAccounts?.length) {
      obj.bankAccounts = message.bankAccounts.map((e) => BankAccount.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetBankAccountsResponse>, I>>(base?: I): GetBankAccountsResponse {
    return GetBankAccountsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetBankAccountsResponse>, I>>(object: I): GetBankAccountsResponse {
    const message = createBaseGetBankAccountsResponse();
    message.status = object.status ?? false;
    message.bankAccounts = object.bankAccounts?.map((e) => BankAccount.fromPartial(e)) || [];
    return message;
  },
};

export interface BankAccountService {
  GetBankAccounts(request: GetBankAccountsRequest): Promise<GetBankAccountsResponse>;
}

export const BankAccountServiceServiceName = "BankAccountService";
export class BankAccountServiceClientImpl implements BankAccountService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || BankAccountServiceServiceName;
    this.rpc = rpc;
    this.GetBankAccounts = this.GetBankAccounts.bind(this);
  }
  GetBankAccounts(request: GetBankAccountsRequest): Promise<GetBankAccountsResponse> {
    const data = GetBankAccountsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetBankAccounts", data);
    return promise.then((data) => GetBankAccountsResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
