// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: src/shared/proto/category.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface GetCategoriesRequest {
  telegramId: number;
}

export interface Category {
  uuid: string;
  title: string;
  emoji: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetCategoriesResponse {
  status: boolean;
  categories: Category[];
}

function createBaseGetCategoriesRequest(): GetCategoriesRequest {
  return { telegramId: 0 };
}

export const GetCategoriesRequest: MessageFns<GetCategoriesRequest> = {
  encode(message: GetCategoriesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.telegramId !== 0) {
      writer.uint32(8).int64(message.telegramId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCategoriesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCategoriesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.telegramId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCategoriesRequest {
    return { telegramId: isSet(object.telegramId) ? globalThis.Number(object.telegramId) : 0 };
  },

  toJSON(message: GetCategoriesRequest): unknown {
    const obj: any = {};
    if (message.telegramId !== 0) {
      obj.telegramId = Math.round(message.telegramId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCategoriesRequest>, I>>(base?: I): GetCategoriesRequest {
    return GetCategoriesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCategoriesRequest>, I>>(object: I): GetCategoriesRequest {
    const message = createBaseGetCategoriesRequest();
    message.telegramId = object.telegramId ?? 0;
    return message;
  },
};

function createBaseCategory(): Category {
  return { uuid: "", title: "", emoji: "", createdAt: "", updatedAt: "" };
}

export const Category: MessageFns<Category> = {
  encode(message: Category, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.emoji !== "") {
      writer.uint32(26).string(message.emoji);
    }
    if (message.createdAt !== "") {
      writer.uint32(34).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(42).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Category {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCategory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.emoji = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Category {
    return {
      uuid: isSet(object.uuid) ? globalThis.String(object.uuid) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      emoji: isSet(object.emoji) ? globalThis.String(object.emoji) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
      updatedAt: isSet(object.updatedAt) ? globalThis.String(object.updatedAt) : "",
    };
  },

  toJSON(message: Category): unknown {
    const obj: any = {};
    if (message.uuid !== "") {
      obj.uuid = message.uuid;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.emoji !== "") {
      obj.emoji = message.emoji;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Category>, I>>(base?: I): Category {
    return Category.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Category>, I>>(object: I): Category {
    const message = createBaseCategory();
    message.uuid = object.uuid ?? "";
    message.title = object.title ?? "";
    message.emoji = object.emoji ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseGetCategoriesResponse(): GetCategoriesResponse {
  return { status: false, categories: [] };
}

export const GetCategoriesResponse: MessageFns<GetCategoriesResponse> = {
  encode(message: GetCategoriesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== false) {
      writer.uint32(8).bool(message.status);
    }
    for (const v of message.categories) {
      Category.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCategoriesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCategoriesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.status = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.categories.push(Category.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetCategoriesResponse {
    return {
      status: isSet(object.status) ? globalThis.Boolean(object.status) : false,
      categories: globalThis.Array.isArray(object?.categories)
        ? object.categories.map((e: any) => Category.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetCategoriesResponse): unknown {
    const obj: any = {};
    if (message.status !== false) {
      obj.status = message.status;
    }
    if (message.categories?.length) {
      obj.categories = message.categories.map((e) => Category.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCategoriesResponse>, I>>(base?: I): GetCategoriesResponse {
    return GetCategoriesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCategoriesResponse>, I>>(object: I): GetCategoriesResponse {
    const message = createBaseGetCategoriesResponse();
    message.status = object.status ?? false;
    message.categories = object.categories?.map((e) => Category.fromPartial(e)) || [];
    return message;
  },
};

export interface CategoryService {
  GetCategories(request: GetCategoriesRequest): Promise<GetCategoriesResponse>;
}

export const CategoryServiceServiceName = "CategoryService";
export class CategoryServiceClientImpl implements CategoryService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || CategoryServiceServiceName;
    this.rpc = rpc;
    this.GetCategories = this.GetCategories.bind(this);
  }
  GetCategories(request: GetCategoriesRequest): Promise<GetCategoriesResponse> {
    const data = GetCategoriesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetCategories", data);
    return promise.then((data) => GetCategoriesResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
