// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: src/proto/telegram.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface ConnectTelegramRequest {
  userUuid: string;
  telegramId: number;
}

export interface ConnectTelegramResponse {
  success: boolean;
  username: string;
}

function createBaseConnectTelegramRequest(): ConnectTelegramRequest {
  return { userUuid: "", telegramId: 0 };
}

export const ConnectTelegramRequest: MessageFns<ConnectTelegramRequest> = {
  encode(message: ConnectTelegramRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userUuid !== "") {
      writer.uint32(10).string(message.userUuid);
    }
    if (message.telegramId !== 0) {
      writer.uint32(16).int64(message.telegramId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectTelegramRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectTelegramRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.telegramId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectTelegramRequest {
    return {
      userUuid: isSet(object.userUuid) ? globalThis.String(object.userUuid) : "",
      telegramId: isSet(object.telegramId) ? globalThis.Number(object.telegramId) : 0,
    };
  },

  toJSON(message: ConnectTelegramRequest): unknown {
    const obj: any = {};
    if (message.userUuid !== "") {
      obj.userUuid = message.userUuid;
    }
    if (message.telegramId !== 0) {
      obj.telegramId = Math.round(message.telegramId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnectTelegramRequest>, I>>(base?: I): ConnectTelegramRequest {
    return ConnectTelegramRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnectTelegramRequest>, I>>(object: I): ConnectTelegramRequest {
    const message = createBaseConnectTelegramRequest();
    message.userUuid = object.userUuid ?? "";
    message.telegramId = object.telegramId ?? 0;
    return message;
  },
};

function createBaseConnectTelegramResponse(): ConnectTelegramResponse {
  return { success: false, username: "" };
}

export const ConnectTelegramResponse: MessageFns<ConnectTelegramResponse> = {
  encode(message: ConnectTelegramResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectTelegramResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectTelegramResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectTelegramResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: ConnectTelegramResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConnectTelegramResponse>, I>>(base?: I): ConnectTelegramResponse {
    return ConnectTelegramResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConnectTelegramResponse>, I>>(object: I): ConnectTelegramResponse {
    const message = createBaseConnectTelegramResponse();
    message.success = object.success ?? false;
    message.username = object.username ?? "";
    return message;
  },
};

export interface TelegramService {
  ConnectTelegram(request: ConnectTelegramRequest): Promise<ConnectTelegramResponse>;
}

export const TelegramServiceServiceName = "TelegramService";
export class TelegramServiceClientImpl implements TelegramService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TelegramServiceServiceName;
    this.rpc = rpc;
    this.ConnectTelegram = this.ConnectTelegram.bind(this);
  }
  ConnectTelegram(request: ConnectTelegramRequest): Promise<ConnectTelegramResponse> {
    const data = ConnectTelegramRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ConnectTelegram", data);
    return promise.then((data) => ConnectTelegramResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
