// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: src/shared/proto/transaction.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface CreateTransactionRequest {
  telegramId: number;
  amount: number;
  description?: string | undefined;
  categoryUuid?: string | undefined;
  bankAccountUuid?: string | undefined;
  currency?: string | undefined;
}

export interface CreateTransactionResponse {
  transactionUuid: string;
  amount: number;
  currency: string;
  bankAccountBalanceInUsd: number;
  categoryUuid: string;
  categoryTitle: string;
  categoryEmoji: string;
  bankAccountUuid: string;
  bankAccountTitle: string;
  bankAccountEmoji: string;
  description?: string | undefined;
}

function createBaseCreateTransactionRequest(): CreateTransactionRequest {
  return {
    telegramId: 0,
    amount: 0,
    description: undefined,
    categoryUuid: undefined,
    bankAccountUuid: undefined,
    currency: undefined,
  };
}

export const CreateTransactionRequest: MessageFns<CreateTransactionRequest> = {
  encode(message: CreateTransactionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.telegramId !== 0) {
      writer.uint32(8).int64(message.telegramId);
    }
    if (message.amount !== 0) {
      writer.uint32(17).double(message.amount);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.categoryUuid !== undefined) {
      writer.uint32(34).string(message.categoryUuid);
    }
    if (message.bankAccountUuid !== undefined) {
      writer.uint32(42).string(message.bankAccountUuid);
    }
    if (message.currency !== undefined) {
      writer.uint32(50).string(message.currency);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTransactionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTransactionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.telegramId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.categoryUuid = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.bankAccountUuid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTransactionRequest {
    return {
      telegramId: isSet(object.telegramId) ? globalThis.Number(object.telegramId) : 0,
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      categoryUuid: isSet(object.categoryUuid) ? globalThis.String(object.categoryUuid) : undefined,
      bankAccountUuid: isSet(object.bankAccountUuid) ? globalThis.String(object.bankAccountUuid) : undefined,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : undefined,
    };
  },

  toJSON(message: CreateTransactionRequest): unknown {
    const obj: any = {};
    if (message.telegramId !== 0) {
      obj.telegramId = Math.round(message.telegramId);
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.categoryUuid !== undefined) {
      obj.categoryUuid = message.categoryUuid;
    }
    if (message.bankAccountUuid !== undefined) {
      obj.bankAccountUuid = message.bankAccountUuid;
    }
    if (message.currency !== undefined) {
      obj.currency = message.currency;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTransactionRequest>, I>>(base?: I): CreateTransactionRequest {
    return CreateTransactionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTransactionRequest>, I>>(object: I): CreateTransactionRequest {
    const message = createBaseCreateTransactionRequest();
    message.telegramId = object.telegramId ?? 0;
    message.amount = object.amount ?? 0;
    message.description = object.description ?? undefined;
    message.categoryUuid = object.categoryUuid ?? undefined;
    message.bankAccountUuid = object.bankAccountUuid ?? undefined;
    message.currency = object.currency ?? undefined;
    return message;
  },
};

function createBaseCreateTransactionResponse(): CreateTransactionResponse {
  return {
    transactionUuid: "",
    amount: 0,
    currency: "",
    bankAccountBalanceInUsd: 0,
    categoryUuid: "",
    categoryTitle: "",
    categoryEmoji: "",
    bankAccountUuid: "",
    bankAccountTitle: "",
    bankAccountEmoji: "",
    description: undefined,
  };
}

export const CreateTransactionResponse: MessageFns<CreateTransactionResponse> = {
  encode(message: CreateTransactionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transactionUuid !== "") {
      writer.uint32(10).string(message.transactionUuid);
    }
    if (message.amount !== 0) {
      writer.uint32(17).double(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(26).string(message.currency);
    }
    if (message.bankAccountBalanceInUsd !== 0) {
      writer.uint32(33).double(message.bankAccountBalanceInUsd);
    }
    if (message.categoryUuid !== "") {
      writer.uint32(42).string(message.categoryUuid);
    }
    if (message.categoryTitle !== "") {
      writer.uint32(50).string(message.categoryTitle);
    }
    if (message.categoryEmoji !== "") {
      writer.uint32(58).string(message.categoryEmoji);
    }
    if (message.bankAccountUuid !== "") {
      writer.uint32(66).string(message.bankAccountUuid);
    }
    if (message.bankAccountTitle !== "") {
      writer.uint32(74).string(message.bankAccountTitle);
    }
    if (message.bankAccountEmoji !== "") {
      writer.uint32(82).string(message.bankAccountEmoji);
    }
    if (message.description !== undefined) {
      writer.uint32(90).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTransactionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTransactionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transactionUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.bankAccountBalanceInUsd = reader.double();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.categoryUuid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.categoryTitle = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.categoryEmoji = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bankAccountUuid = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.bankAccountTitle = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.bankAccountEmoji = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTransactionResponse {
    return {
      transactionUuid: isSet(object.transactionUuid) ? globalThis.String(object.transactionUuid) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      bankAccountBalanceInUsd: isSet(object.bankAccountBalanceInUsd)
        ? globalThis.Number(object.bankAccountBalanceInUsd)
        : 0,
      categoryUuid: isSet(object.categoryUuid) ? globalThis.String(object.categoryUuid) : "",
      categoryTitle: isSet(object.categoryTitle) ? globalThis.String(object.categoryTitle) : "",
      categoryEmoji: isSet(object.categoryEmoji) ? globalThis.String(object.categoryEmoji) : "",
      bankAccountUuid: isSet(object.bankAccountUuid) ? globalThis.String(object.bankAccountUuid) : "",
      bankAccountTitle: isSet(object.bankAccountTitle) ? globalThis.String(object.bankAccountTitle) : "",
      bankAccountEmoji: isSet(object.bankAccountEmoji) ? globalThis.String(object.bankAccountEmoji) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
    };
  },

  toJSON(message: CreateTransactionResponse): unknown {
    const obj: any = {};
    if (message.transactionUuid !== "") {
      obj.transactionUuid = message.transactionUuid;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.bankAccountBalanceInUsd !== 0) {
      obj.bankAccountBalanceInUsd = message.bankAccountBalanceInUsd;
    }
    if (message.categoryUuid !== "") {
      obj.categoryUuid = message.categoryUuid;
    }
    if (message.categoryTitle !== "") {
      obj.categoryTitle = message.categoryTitle;
    }
    if (message.categoryEmoji !== "") {
      obj.categoryEmoji = message.categoryEmoji;
    }
    if (message.bankAccountUuid !== "") {
      obj.bankAccountUuid = message.bankAccountUuid;
    }
    if (message.bankAccountTitle !== "") {
      obj.bankAccountTitle = message.bankAccountTitle;
    }
    if (message.bankAccountEmoji !== "") {
      obj.bankAccountEmoji = message.bankAccountEmoji;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTransactionResponse>, I>>(base?: I): CreateTransactionResponse {
    return CreateTransactionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTransactionResponse>, I>>(object: I): CreateTransactionResponse {
    const message = createBaseCreateTransactionResponse();
    message.transactionUuid = object.transactionUuid ?? "";
    message.amount = object.amount ?? 0;
    message.currency = object.currency ?? "";
    message.bankAccountBalanceInUsd = object.bankAccountBalanceInUsd ?? 0;
    message.categoryUuid = object.categoryUuid ?? "";
    message.categoryTitle = object.categoryTitle ?? "";
    message.categoryEmoji = object.categoryEmoji ?? "";
    message.bankAccountUuid = object.bankAccountUuid ?? "";
    message.bankAccountTitle = object.bankAccountTitle ?? "";
    message.bankAccountEmoji = object.bankAccountEmoji ?? "";
    message.description = object.description ?? undefined;
    return message;
  },
};

export interface TransactionService {
  CreateTransaction(request: CreateTransactionRequest): Promise<CreateTransactionResponse>;
}

export const TransactionServiceServiceName = "TransactionService";
export class TransactionServiceClientImpl implements TransactionService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || TransactionServiceServiceName;
    this.rpc = rpc;
    this.CreateTransaction = this.CreateTransaction.bind(this);
  }
  CreateTransaction(request: CreateTransactionRequest): Promise<CreateTransactionResponse> {
    const data = CreateTransactionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateTransaction", data);
    return promise.then((data) => CreateTransactionResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
