FROM maven:3.9.4-eclipse-temurin-20

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

RUN apt-get update && apt-get install -y curl \
 && curl -L https://github.com/watchexec/watchexec/releases/download/1.19.1/watchexec-1.19.1-x86_64-unknown-linux-gnu.deb -o /tmp/watchexec.deb \
 && dpkg -i /tmp/watchexec.deb \
 && rm /tmp/watchexec.deb

EXPOSE 8080

CMD ["watchexec", "-r", "-e", "java", "--", "mvn", "compile", "spring-boot:run", "-Dspring-boot.run.fork=false"]
